SOURCE/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Date_OF_Birth__c</fullName>
        <label>Date OF Birth</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SSN__c</fullName>
        <label>SSN</label>
        <length>9</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prospecting</fullName>
                    <default>true</default>
                    <label>Prospecting</label>
                </value>
                <value>
                    <fullName>Building</fullName>
                </value>
                <value>
                    <fullName>Established</fullName>
                </value>
                <value>
                    <fullName>Preferred Referral Partner</fullName>
                </value>
                <value>
                    <fullName>Enterprise Account</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

SOURCE/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Caller_Email__c</fullName>
        <label>Caller Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City Sub</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_DOB__c</fullName>
        <label>Patient DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client_First_Name__c</fullName>
        <label>Patient First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Full_Name__c</fullName>
        <description>merge first name middle name and last name</description>
        <formula>Client_First_Name__c+&apos; &apos;+ Client_Middle_Name__c +&apos; &apos;+ Client_Last_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Last_Name__c</fullName>
        <label>Patient Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Middle_Name__c</fullName>
        <label>Patient Middle Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Phone__c</fullName>
        <label>Patient Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group #</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Insurance_Provider_lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Insurance Provider</label>
        <referenceTo>Payor__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Member_ID__c</fullName>
        <label>Member ID #</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SSN__c</fullName>
        <label>SSN</label>
        <length>50</length>
        <maskChar>asterisk</maskChar>
        <maskType>ssn</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Secondary_Group__c</fullName>
        <label>Secondary Group #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Insurance_Provide__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Secondary Insurance Provider</label>
        <referenceTo>Payor__c</referenceTo>
        <relationshipLabel>Leads (Secondary Insurance Provide)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Secondary_Member_ID__c</fullName>
        <label>Secondary Member ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Test_DOB__c</fullName>
        <formula>Text(Client_DOB__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Test_DOB</label>
        <type>Text</type>
    </fields>
</CustomObject>

SOURCE/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Caller_Email__c</fullName>
        <label>Caller Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Caller_First_Name__c</fullName>
        <label>Caller First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Caller_Last_Name__c</fullName>
        <label>Caller Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_DOB__c</fullName>
        <label>Patient DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client_Email__c</fullName>
        <label>Patient Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Client_First_Name__c</fullName>
        <label>Patient First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Last_Name__c</fullName>
        <label>Patient Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Middle_Name__c</fullName>
        <label>Patient Middle Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>United States</fullName>
                    <default>true</default>
                    <label>United States</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Has_Secondary_Insurance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Secondary Insurance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SSN__c</fullName>
        <label>SSN</label>
        <length>50</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Secondary_Group__c</fullName>
        <label>Secondary Group #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Member_ID__c</fullName>
        <label>Secondary Member ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

SOURCE/objects/VOB__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_DOB__c</fullName>
        <label>Patient DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client_First_Name__c</fullName>
        <label>Patient First Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Last_Name__c</fullName>
        <label>Patient Last Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Group_Number_New__c</fullName>
        <label>Group Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group #</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Insurance_Provider_lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Insurance Provider</label>
        <referenceTo>Payor__c</referenceTo>
        <relationshipLabel>VOBs</relationshipLabel>
        <relationshipName>VOBs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Member_ID_New__c</fullName>
        <label>Member ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_Id__c</fullName>
        <label>Member Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Patient_Name_admission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>When choose a patient name, demographic details and insurance details auto filled</inlineHelpText>
        <label>Patient Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>VOB</relationshipLabel>
        <relationshipName>VOBs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>VOB In Queue</fullName>
                    <default>true</default>
                    <label>VOB In Queue</label>
                </value>
                <value>
                    <fullName>VOB Requested</fullName>
                </value>
                <value>
                    <fullName>VOB Pending</fullName>
                </value>
                <value>
                    <fullName>VOB Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subs_Address__c</fullName>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>VOB</label>
    <nameField>
        <displayFormat>VOB-{0000}</displayFormat>
        <label>VOB Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VOBs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SOURCE/classes/UpdateOpportunity.cls
public class UpdateOpportunity {
    
    public static void methodToMap(List<Lead> leads)
    {
         Map<id,Lead> oppIDLeadMap = new Map<id,Lead>();
         List<Opportunity> OpptoInsert = new List<Opportunity>();
         List<VOB__c> vobToInsert = new List<VOB__c>();
        List<Account> acctInsert=new List<Account>();
        List<Contact> conInsert=new List<contact>();
        
         for(Lead ld:leads){
             if(ld.isConverted==true){
               oppIDLeadMap.put(ld.ConvertedOpportunityId, ld);
                 if(ld.ConvertedOpportunityId!=null){
                     
                  if(ld.Has_Insurance__c== false){
                    OpptoInsert.add(new Opportunity(id = ld.ConvertedOpportunityId,Name=ld.Client_Full_Name__c,Client_Email__c=ld.Email,Caller_First_Name__c=ld.FirstName, Caller_Last_Name__c=ld.LastName,
                          StageName = 'Active',Caller_Email__c = ld.Caller_Email__c,SSN__c = ld.SSN__c,Street__c=ld.Street,City__c=ld.City,Zip__c=ld.PostalCode,
                                                    State1__c=ld.State,Country__c=ld.Country,CampaignId=ld.Campaign__c));
                  }
                  else {
                 OpptoInsert.add(new Opportunity(id = ld.ConvertedOpportunityId,Name=ld.Client_Full_Name__c,Client_Email__c=ld.Email, StageName = 'VOB In Queue',Caller_First_Name__c=ld.FirstName, Caller_Last_Name__c=ld.LastName,
                                                 Caller_Email__c = ld.Caller_Email__c,SSN__c = ld.SSN__c,Street__c=ld.Street,City__c=ld.City,Zip__c=ld.PostalCode,
                                                 State1__c=ld.State,Country__c=ld.Country,CampaignId=ld.Campaign__c));
                  //system.debug('YES');
                  }
                 if(ld.Company==null){
                 acctInsert.add(new Account(id = ld.ConvertedAccountId,FirstName = ld.Client_First_Name__c, 
                                             MiddleName =ld.Client_Middle_Name__c, LastName=ld.Client_Last_Name__c,Phone=ld.Client_Phone__c,Date_OF_Birth__c=ld.Test_DOB__c));}
                 else{
                     acctInsert.add(new Account(id=ld.ConvertedAccountId,Name=ld.Company,Phone=ld.Client_Phone__c));
                     conInsert.add(new Contact(id=ld.ConvertedContactId, firstName=ld.Client_First_Name__c,MiddleName=ld.Client_Middle_Name__c
                                              ,LastName=ld.Client_Last_Name__c));
                 }}
                     
                else{
                     if(ld.Company==null){
                 acctInsert.add(new Account(id = ld.ConvertedAccountId,FirstName = ld.Client_First_Name__c, 
                                             MiddleName =ld.Client_Middle_Name__c, LastName=ld.Client_Last_Name__c,
                                            Phone=ld.Client_Phone__c));
                     }
                 else{
                     acctInsert.add(new Account(id=ld.ConvertedAccountId,Name=ld.Company,Phone=ld.Client_Phone__c));
                     conInsert.add(new Contact(id=ld.ConvertedContactId, firstName=ld.Client_First_Name__c,MiddleName=ld.Client_Middle_Name__c
                                              ,LastName=ld.Client_Last_Name__c));
                     }
                      
                  }
            
             }
         }
         update OpptoInsert;  
         update acctInsert;
        update conInsert;
        for(ID oppid:oppIDLeadMap.keySet()){
            Lead l=oppIDLeadMap.get(oppid);
          if(l.ConvertedOpportunityId!=null){
            if(l.Has_Insurance__c==True){
                
                VOB__c vob1=new VOB__c();
                vob1.Patient_Name_admission__c= oppId;
                vob1.Stage__c = 'VOB In Queue';
                vob1.Client_First_Name__c=l.Client_First_Name__c;
                vob1.Client_Last_Name__c=l.Client_Last_Name__c;
                vob1.Client_DOB__c=l.Client_DOB__c;
                vob1.Email__c=l.Email;
                vob1.Phone__c=l.Phone;
                  
                string add1=l.Country+','+l.State+','+l.Street+','+l.City+','+l.PostalCode;
                List<string> addList=add1.split(',');
                string[] addfinal=new string[]{};
                string append1;
                for(string s: addList){
                    
                    if(s!='NULL'){
                        addfinal.add(s);
                    }
                }
                append1=string.join(addfinal,',');
                vob1.Subs_Address__c=append1;
                system.debug('Address is->'+vob1.Subs_Address__c);
                
                vob1.Insurance_Provider_lookup__c=l.Insurance_Provider_lookup__c;
                System.debug('Pri_Insurance_Provide__c '+l.Insurance_Provider_lookup__c);
                vob1.Member_ID_New__c=l.Member_ID__c;
                vob1.Group_Number_New__c=l.Group__c;
                
                vobToInsert.add(vob1);
                system.debug('List is'+vobToInsert);
                system.debug('Primary vob is:'+vob1);
                
            }
              if(l.Has_Secondary_Insurance__c==true){
                   
                VOB__c vob=new VOB__c();
                vob.Patient_Name_admission__c= oppId;
                vob.Stage__c = 'VOB In Queue';
                vob.Client_First_Name__c=l.Client_First_Name__c;
                vob.Client_Last_Name__c=l.Client_Last_Name__c;
                vob.Client_DOB__c=l.Client_DOB__c;
                vob.Email__c=l.Email;
                vob.Phone__c=l.Phone;
  
                string add1=l.Country+','+l.State+','+l.Street+','+l.City+','+l.PostalCode;
                List<string> addList=add1.split(',');
                string[] addfinal=new string[]{};
                string append1;
                for(string s: addList){
                    
                    if(s!='NULL'){
                        addfinal.add(s);
                    }
                }
                append1=string.join(addfinal,',');
                vob.Subs_Address__c=append1;
                system.debug('Address is->'+vob.Subs_Address__c);
                
                vob.Insurance_Provider_lookup__c=l.Secondary_Insurance_Provide__c;
                System.debug('Secondary_Insurance_Provide__c '+l.Secondary_Insurance_Provide__c);
                vob.Member_ID_New__c=l.Secondary_Member_ID__c;
                vob.Group_Number_New__c=l.Secondary_Group__c;
                vobToInsert.add(vob);
                system.debug('List is'+vobToInsert);
                  system.debug('Secondary vob is:'+vob);
                  
                 
              }
              
            }
            insert vobToInsert;
            update vobToInsert;
          }
            
        }
              
   }