SOURCE/objects/Medication_History__c.object
<CustomObject>
    <fields>
        <fullName>Current_Compliance__c</fullName>
        <label>Current Compliance</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_of_Last_Use__c</fullName>
        <label>Date of Last Use</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Dosage__c</fullName>
        <label>Dosage</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <label>Frequency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Length_of_Prescription__c</fullName>
        <label>Length of Prescription</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_of_the_Medication__c</fullName>
        <label>Name of the Medication</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accuneb: Proventil</fullName>
                </value>
                <value>
                    <fullName>Actos</fullName>
                </value>
                <value>
                    <fullName>Adderall XR</fullName>
                </value>
                <value>
                    <fullName>Advair</fullName>
                </value>
                <value>
                    <fullName>Aldactone</fullName>
                </value>
                <value>
                    <fullName>Allegra</fullName>
                </value>
                <value>
                    <fullName>Amaryl</fullName>
                </value>
                <value>
                    <fullName>Ambien</fullName>
                </value>
                <value>
                    <fullName>Amoxil: Trimox</fullName>
                </value>
                <value>
                    <fullName>Aristocort;Cinalog;Kenalog;Triderm</fullName>
                </value>
                <value>
                    <fullName>Ativan</fullName>
                </value>
                <value>
                    <fullName>Augmentin</fullName>
                </value>
                <value>
                    <fullName>Bactrim DS;Septra DS</fullName>
                </value>
                <value>
                    <fullName>Calan SR;Verelan PM</fullName>
                </value>
                <value>
                    <fullName>Catapres</fullName>
                </value>
                <value>
                    <fullName>Celebrex</fullName>
                </value>
                <value>
                    <fullName>Celexa</fullName>
                </value>
                <value>
                    <fullName>Cipro</fullName>
                </value>
                <value>
                    <fullName>Coreg</fullName>
                </value>
                <value>
                    <fullName>Cozaar</fullName>
                </value>
                <value>
                    <fullName>Crestor</fullName>
                </value>
                <value>
                    <fullName>Cymbalta</fullName>
                </value>
                <value>
                    <fullName>Deltasone</fullName>
                </value>
                <value>
                    <fullName>Desyrel</fullName>
                </value>
                <value>
                    <fullName>Diabeta</fullName>
                </value>
                <value>
                    <fullName>Diflucan</fullName>
                </value>
                <value>
                    <fullName>Diovan</fullName>
                </value>
                <value>
                    <fullName>Dyazide;Maxzide</fullName>
                </value>
                <value>
                    <fullName>Effexor XR</fullName>
                </value>
                <value>
                    <fullName>Elavil</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pre_Assessment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pre-Assessment</label>
        <referenceTo>PreAssesment__c</referenceTo>
        <relationshipLabel>Medication History</relationshipLabel>
        <relationshipName>Medication_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Medication History</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Medication History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medication History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SOURCE/objects/Substance_Abuse_History__c.object
<CustomObject>
    <fields>
        <fullName>Age_of_first_use__c</fullName>
        <label>Age of first use</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Daily_Amount__c</fullName>
        <label>Daily Amount</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Drug__c</fullName>
        <label>Substance Used</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alcohol</fullName>
                </value>
                <value>
                    <fullName>LSD</fullName>
                </value>
                <value>
                    <fullName>Mushrooms</fullName>
                </value>
                <value>
                    <fullName>Ecstasy</fullName>
                </value>
                <value>
                    <fullName>Marijuana</fullName>
                </value>
                <value>
                    <fullName>Heroin</fullName>
                </value>
                <value>
                    <fullName>Klonopin</fullName>
                </value>
                <value>
                    <fullName>Cocaine</fullName>
                </value>
                <value>
                    <fullName>Barbiturates</fullName>
                </value>
                <value>
                    <fullName>Valium</fullName>
                </value>
                <value>
                    <fullName>Ativan</fullName>
                </value>
                <value>
                    <fullName>Xanax</fullName>
                </value>
                <value>
                    <fullName>Librium</fullName>
                </value>
                <value>
                    <fullName>Crack Cocaine</fullName>
                </value>
                <value>
                    <fullName>Crystal Meth</fullName>
                </value>
                <value>
                    <fullName>Bath Salts</fullName>
                </value>
                <value>
                    <fullName>Adderall</fullName>
                </value>
                <value>
                    <fullName>Caffeine</fullName>
                </value>
                <value>
                    <fullName>Cigarettes</fullName>
                </value>
                <value>
                    <fullName>PCP</fullName>
                </value>
                <value>
                    <fullName>Angel Dust</fullName>
                </value>
                <value>
                    <fullName>Synthetic Marijuana</fullName>
                </value>
                <value>
                    <fullName>THC</fullName>
                </value>
                <value>
                    <fullName>Acid</fullName>
                </value>
                <value>
                    <fullName>Fentanyl</fullName>
                </value>
                <value>
                    <fullName>Percocet</fullName>
                </value>
                <value>
                    <fullName>Morphine</fullName>
                </value>
                <value>
                    <fullName>Kratom</fullName>
                </value>
                <value>
                    <fullName>Vicodin</fullName>
                </value>
                <value>
                    <fullName>Dilaudid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <label>Frequency</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Last_Use__c</fullName>
        <label>Last Use</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Orally</fullName>
                </value>
                <value>
                    <fullName>Intravenously</fullName>
                </value>
                <value>
                    <fullName>Intramusculary</fullName>
                </value>
                <value>
                    <fullName>Nasally</fullName>
                </value>
                <value>
                    <fullName>Inhalation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pre_Assessment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pre-Assessment</label>
        <referenceTo>PreAssesment__c</referenceTo>
        <relationshipLabel>Substance Abuse History</relationshipLabel>
        <relationshipName>Substance_Abuse_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Substance Abuse History</label>
    <nameField>
        <displayFormat>SAH-{000}</displayFormat>
        <label>Substance Abuse History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Substance Abuse History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SOURCE/objects/Treatment_History__c.object
<CustomObject>
    <fields>
        <fullName>Date_of_Episode__c</fullName>
        <label>Date of Episode</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Facility__c</fullName>
        <label>Facility</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Length_of_Sobriety_Achieved__c</fullName>
        <label>Length of Sobriety Achieved</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Length_of_Stay__c</fullName>
        <label>Length of Stay</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level_Of_Care__c</fullName>
        <label>Level Of Care</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Detox</fullName>
                </value>
                <value>
                    <fullName>Residential</fullName>
                </value>
                <value>
                    <fullName>IOP</fullName>
                </value>
                <value>
                    <fullName>Day-Night/PHP</fullName>
                </value>
                <value>
                    <fullName>OP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pre_Assessment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pre-Assessment</label>
        <referenceTo>PreAssesment__c</referenceTo>
        <relationshipLabel>Treatment History</relationshipLabel>
        <relationshipName>Treatment_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type_of_Discharge__c</fullName>
        <label>Type of Discharge</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Completed Successfully</fullName>
                </value>
                <value>
                    <fullName>AMA</fullName>
                </value>
                <value>
                    <fullName>Therapeutic Discharge</fullName>
                </value>
                <value>
                    <fullName>Therapeutic Transfer</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Treatment History</label>
    <nameField>
        <displayFormat>TH-{000}</displayFormat>
        <label>Treatment History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SOURCE/classes/PdfHelper.cls
public class PdfHelper {
   

public static List<Substance_Abuse_History__c> SubstanceList {get;set;}
    public static List<Medication_History__c> SubstanceList1 {get;set;}
     public static List<Treatment_History__c> TreatmentList {get;set;}



public static String currentRecordId {get;set;}
  //  public static List<Substance_Abuse_History__c> fetchmeth1 {get;set;}
 
    public PdfHelper (ApexPages.StandardController controller) {
    
        currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');
        system.debug('id-->'+currentRecordId  );
 
    }


public static List<Substance_Abuse_History__c> getmeth1() {
//public static List<Substance_Abuse_History__c> fetchmeth1() {

        SubstanceList = new List<Substance_Abuse_History__c>([select id,Drug__c,OwnerId,Last_Use__c,Daily_Amount__c,Pre_Assessment__c,CreatedById,LastModifiedById,Method__c,Name, Age_of_first_use__c,Frequency__c from Substance_Abuse_History__c where Pre_Assessment__c=: currentRecordId]);
        return SubstanceList ;

}
public static List<Medication_History__c> getmeth2() {
//public static List<Substance_Abuse_History__c> fetchmeth1() {

        SubstanceList1 = new List<Medication_History__c>([select id,Pre_Assessment__c,Date_of_Last_Use__c,CreatedById,LastModifiedById,Frequency__c,Current_Compliance__c,Length_of_Prescription__c,Name_of_the_Medication__c,Dosage__c,Name from Medication_History__c where Pre_Assessment__c=: currentRecordId]);
        return SubstanceList1 ;

}
    public static List<Treatment_History__c> getmeth3() {
//public static List<Substance_Abuse_History__c> fetchmeth1() {

        TreatmentList = new List<Treatment_History__c>([select id, Level_Of_Care__c,OwnerId,Facility__c,Length_of_Sobriety_Achieved__c,Name,Type_of_Discharge__c,Pre_Assessment__c,CreatedById,LastModifiedById,Length_of_Stay__c,Date_of_Episode__c from Treatment_History__c where Pre_Assessment__c=: currentRecordId]);
        return TreatmentList ;

}



}