SOURCE/objects/Medication_History__c.object
<CustomObject>
    <fields>
        <fullName>Frequency__c</fullName>
        <label>Frequency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_of_the_Medication__c</fullName>
        <label>Name of the Medication</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accuneb: Proventil</fullName>
                </value>
                <value>
                    <fullName>Actos</fullName>
                </value>
                <value>
                    <fullName>Adderall XR</fullName>
                </value>
                <value>
                    <fullName>Advair</fullName>
                </value>
                <value>
                    <fullName>Aldactone</fullName>
                </value>
                <value>
                    <fullName>Allegra</fullName>
                </value>
                <value>
                    <fullName>Amaryl</fullName>
                </value>
                <value>
                    <fullName>Ambien</fullName>
                </value>
                <value>
                    <fullName>Amoxil: Trimox</fullName>
                </value>
                <value>
                    <fullName>Aristocort;Cinalog;Kenalog;Triderm</fullName>
                </value>
                <value>
                    <fullName>Ativan</fullName>
                </value>
                <value>
                    <fullName>Augmentin</fullName>
                </value>
                <value>
                    <fullName>Bactrim DS;Septra DS</fullName>
                </value>
                <value>
                    <fullName>Calan SR;Verelan PM</fullName>
                </value>
                <value>
                    <fullName>Catapres</fullName>
                </value>
                <value>
                    <fullName>Celebrex</fullName>
                </value>
                <value>
                    <fullName>Celexa</fullName>
                </value>
                <value>
                    <fullName>Cipro</fullName>
                </value>
                <value>
                    <fullName>Coreg</fullName>
                </value>
                <value>
                    <fullName>Cozaar</fullName>
                </value>
                <value>
                    <fullName>Crestor</fullName>
                </value>
                <value>
                    <fullName>Cymbalta</fullName>
                </value>
                <value>
                    <fullName>Deltasone</fullName>
                </value>
                <value>
                    <fullName>Desyrel</fullName>
                </value>
                <value>
                    <fullName>Diabeta</fullName>
                </value>
                <value>
                    <fullName>Diflucan</fullName>
                </value>
                <value>
                    <fullName>Diovan</fullName>
                </value>
                <value>
                    <fullName>Dyazide;Maxzide</fullName>
                </value>
                <value>
                    <fullName>Effexor XR</fullName>
                </value>
                <value>
                    <fullName>Elavil</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Medication History</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Medication History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medication History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SOURCE/objects/Substance_Abuse_History__c.object
<CustomObject>
    <fields>
        <fullName>Drug__c</fullName>
        <label>Substance Used</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alcohol</fullName>
                </value>
                <value>
                    <fullName>LSD</fullName>
                </value>
                <value>
                    <fullName>Mushrooms</fullName>
                </value>
                <value>
                    <fullName>Ecstasy</fullName>
                </value>
                <value>
                    <fullName>Marijuana</fullName>
                </value>
                <value>
                    <fullName>Heroin</fullName>
                </value>
                <value>
                    <fullName>Klonopin</fullName>
                </value>
                <value>
                    <fullName>Cocaine</fullName>
                </value>
                <value>
                    <fullName>Barbiturates</fullName>
                </value>
                <value>
                    <fullName>Valium</fullName>
                </value>
                <value>
                    <fullName>Ativan</fullName>
                </value>
                <value>
                    <fullName>Xanax</fullName>
                </value>
                <value>
                    <fullName>Librium</fullName>
                </value>
                <value>
                    <fullName>Crack Cocaine</fullName>
                </value>
                <value>
                    <fullName>Crystal Meth</fullName>
                </value>
                <value>
                    <fullName>Bath Salts</fullName>
                </value>
                <value>
                    <fullName>Adderall</fullName>
                </value>
                <value>
                    <fullName>Caffeine</fullName>
                </value>
                <value>
                    <fullName>Cigarettes</fullName>
                </value>
                <value>
                    <fullName>PCP</fullName>
                </value>
                <value>
                    <fullName>Angel Dust</fullName>
                </value>
                <value>
                    <fullName>Synthetic Marijuana</fullName>
                </value>
                <value>
                    <fullName>THC</fullName>
                </value>
                <value>
                    <fullName>Acid</fullName>
                </value>
                <value>
                    <fullName>Fentanyl</fullName>
                </value>
                <value>
                    <fullName>Percocet</fullName>
                </value>
                <value>
                    <fullName>Morphine</fullName>
                </value>
                <value>
                    <fullName>Kratom</fullName>
                </value>
                <value>
                    <fullName>Vicodin</fullName>
                </value>
                <value>
                    <fullName>Dilaudid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <label>Frequency</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Orally</fullName>
                </value>
                <value>
                    <fullName>Intravenously</fullName>
                </value>
                <value>
                    <fullName>Intramusculary</fullName>
                </value>
                <value>
                    <fullName>Nasally</fullName>
                </value>
                <value>
                    <fullName>Inhalation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Substance Abuse History</label>
    <nameField>
        <displayFormat>SAH-{000}</displayFormat>
        <label>Substance Abuse History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Substance Abuse History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SOURCE/classes/PreAssesment_SHA_PTH_MH_TH.cls
public class PreAssesment_SHA_PTH_MH_TH {
@AuraEnabled
    public static void saveSubsanceAbuseHistoryRecords(List<Substance_Abuse_History__c> Records){
        System.debug('Subsance Abuse History Records-->'+Records);        
        Insert Records;
    }
    
    @AuraEnabled
    public static void saveSMedicalHistoryRecords(List<Medication_History__c> Records){
        System.debug('Medical History Records---->'+Records);        
        Insert Records;
    }
   @AuraEnabled
    public static List<List<string>> getPickListValuesforMedication(){
        
        List<List<string>> masterList=new List<List<string>>();
        List<string> options=new List<string>();
        Schema.DescribeFieldResult fieldResult = Medication_History__c.Name_of_the_Medication__c.getDescribe();
         List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry f : ple)
        { 
            options.add( f.getValue());
      
        }    
        masterList.add(options);
        return masterList;
        
    }
    @AuraEnabled        
    public static List<List<String>> getPickListValuesIntoListforSAH()
    {
       List<List<string>> masterList = new List<List<string>>();
        List<string> options = new List<string>();
         List<string> options2 = new List<string>();
         List<string> options3 = new List<string>();
        
       
        //String a= 'Primary_Drug_Type__c';
         Schema.DescribeFieldResult fieldResult = Substance_Abuse_History__c.Drug__c.getDescribe();
         Schema.DescribeFieldResult fieldResultsub = Substance_Abuse_History__c.Method__c.getDescribe();
        // Schema.DescribeFieldResult Frequency = Substance_Abuse_History__c.Frequency__c.getDescribe();
           // system.debug('Frequency--->'+Frequency);    
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry f : ple)
        { 
            options.add( f.getValue());
      
        }    
        masterList.add(options);
        
          List<Schema.PicklistEntry> plesub = fieldResultsub.getPicklistValues();
        for( Schema.PicklistEntry fsub : plesub)
        {
            
            options2.add( fsub.getValue());
           
        }     
       masterList.add(options2);
  
       /** List<Schema.PicklistEntry> plesubnext = Frequency.getPicklistValues();
        for( Schema.PicklistEntry ff : plesubnext)
        {
            
            options3.add( ff.getValue());
           
        }     
        masterList.add(options3);
         system.debug('masterList--->'+masterList); **/
  
        return masterList;
   
    }
}