SOURCE/objects/Medication_History__c.object
<CustomObject>
    <fields>
        <fullName>Frequency__c</fullName>
        <label>Frequency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_of_the_Medication__c</fullName>
        <label>Name of the Medication</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accuneb: Proventil</fullName>
                </value>
                <value>
                    <fullName>Actos</fullName>
                </value>
                <value>
                    <fullName>Adderall XR</fullName>
                </value>
                <value>
                    <fullName>Advair</fullName>
                </value>
                <value>
                    <fullName>Aldactone</fullName>
                </value>
                <value>
                    <fullName>Allegra</fullName>
                </value>
                <value>
                    <fullName>Amaryl</fullName>
                </value>
                <value>
                    <fullName>Ambien</fullName>
                </value>
                <value>
                    <fullName>Amoxil: Trimox</fullName>
                </value>
                <value>
                    <fullName>Aristocort;Cinalog;Kenalog;Triderm</fullName>
                </value>
                <value>
                    <fullName>Ativan</fullName>
                </value>
                <value>
                    <fullName>Augmentin</fullName>
                </value>
                <value>
                    <fullName>Bactrim DS;Septra DS</fullName>
                </value>
                <value>
                    <fullName>Calan SR;Verelan PM</fullName>
                </value>
                <value>
                    <fullName>Catapres</fullName>
                </value>
                <value>
                    <fullName>Celebrex</fullName>
                </value>
                <value>
                    <fullName>Celexa</fullName>
                </value>
                <value>
                    <fullName>Cipro</fullName>
                </value>
                <value>
                    <fullName>Coreg</fullName>
                </value>
                <value>
                    <fullName>Cozaar</fullName>
                </value>
                <value>
                    <fullName>Crestor</fullName>
                </value>
                <value>
                    <fullName>Cymbalta</fullName>
                </value>
                <value>
                    <fullName>Deltasone</fullName>
                </value>
                <value>
                    <fullName>Desyrel</fullName>
                </value>
                <value>
                    <fullName>Diabeta</fullName>
                </value>
                <value>
                    <fullName>Diflucan</fullName>
                </value>
                <value>
                    <fullName>Diovan</fullName>
                </value>
                <value>
                    <fullName>Dyazide;Maxzide</fullName>
                </value>
                <value>
                    <fullName>Effexor XR</fullName>
                </value>
                <value>
                    <fullName>Elavil</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Medication History</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Medication History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medication History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SOURCE/objects/PreAssesment__c.object
<CustomObject>
    <fields>
        <fullName>Patient_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Pre-Assessments</relationshipLabel>
        <relationshipName>Pre_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pre-Assessment</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>PreAssesment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pre-Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SOURCE/objects/Substance_Abuse_History__c.object
<CustomObject>
    <fields>
        <fullName>Age_of_first_use__c</fullName>
        <label>Age of first use</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Daily_Amount__c</fullName>
        <label>Daily Amount</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Drug__c</fullName>
        <label>Substance Used</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alcohol</fullName>
                </value>
                <value>
                    <fullName>LSD</fullName>
                </value>
                <value>
                    <fullName>Mushrooms</fullName>
                </value>
                <value>
                    <fullName>Ecstasy</fullName>
                </value>
                <value>
                    <fullName>Marijuana</fullName>
                </value>
                <value>
                    <fullName>Heroin</fullName>
                </value>
                <value>
                    <fullName>Klonopin</fullName>
                </value>
                <value>
                    <fullName>Cocaine</fullName>
                </value>
                <value>
                    <fullName>Barbiturates</fullName>
                </value>
                <value>
                    <fullName>Valium</fullName>
                </value>
                <value>
                    <fullName>Ativan</fullName>
                </value>
                <value>
                    <fullName>Xanax</fullName>
                </value>
                <value>
                    <fullName>Librium</fullName>
                </value>
                <value>
                    <fullName>Crack Cocaine</fullName>
                </value>
                <value>
                    <fullName>Crystal Meth</fullName>
                </value>
                <value>
                    <fullName>Bath Salts</fullName>
                </value>
                <value>
                    <fullName>Adderall</fullName>
                </value>
                <value>
                    <fullName>Caffeine</fullName>
                </value>
                <value>
                    <fullName>Cigarettes</fullName>
                </value>
                <value>
                    <fullName>PCP</fullName>
                </value>
                <value>
                    <fullName>Angel Dust</fullName>
                </value>
                <value>
                    <fullName>Synthetic Marijuana</fullName>
                </value>
                <value>
                    <fullName>THC</fullName>
                </value>
                <value>
                    <fullName>Acid</fullName>
                </value>
                <value>
                    <fullName>Fentanyl</fullName>
                </value>
                <value>
                    <fullName>Percocet</fullName>
                </value>
                <value>
                    <fullName>Morphine</fullName>
                </value>
                <value>
                    <fullName>Kratom</fullName>
                </value>
                <value>
                    <fullName>Vicodin</fullName>
                </value>
                <value>
                    <fullName>Dilaudid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <label>Frequency</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Last_Use__c</fullName>
        <label>Last Use</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Orally</fullName>
                </value>
                <value>
                    <fullName>Intravenously</fullName>
                </value>
                <value>
                    <fullName>Intramusculary</fullName>
                </value>
                <value>
                    <fullName>Nasally</fullName>
                </value>
                <value>
                    <fullName>Inhalation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Substance Abuse History</label>
    <nameField>
        <displayFormat>SAH-{000}</displayFormat>
        <label>Substance Abuse History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Substance Abuse History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SOURCE/classes/PreAssesment_SHA_Test.cls
@istest
public class PreAssesment_SHA_Test {
   @isTest
    static void saveSubsanceAbuseHistoryRecords()
    {
        Test.startTest();
        Substance_Abuse_History__c ob=new Substance_Abuse_History__c();
        List<Substance_Abuse_History__c> result=new List<Substance_Abuse_History__c>();
        Account ac=new Account();
            
        ac.Name='Mr. ab bc cd';
        insert ac;
         Opportunity op=new Opportunity();
         op.Name='av';
      
         op.CloseDate=System.today();
        op.StageName='Active';
        op.AccountId=ac.Id;
        insert op;
        PreAssesment__c ob1=new PreAssesment__c();
        ob1.Patient_Name__c=op.Id;
        insert ob1;
        ob.Drug__c='LSD';
        ob.Method__c='Oral';
        ob.Last_Use__c=system.today();
        ob.Daily_Amount__c='Rare';
        ob.Frequency__c='Daily';
        ob.Age_of_first_use__c ='Detox';
            
        result.add(ob);
        PreAssesment_SHA_PTH_MH_TH.saveSubsanceAbuseHistoryRecords(result);
        Test.stopTest();
    }
    @isTest
    static void TestgetPickListValuesIntoListforSAH()
    {
        Test.startTest();
        Substance_Abuse_History__c ob2=new Substance_Abuse_History__c();
        ob2.Drug__c='LSD';
        ob2.Method__c='Oral';
       // ob2.Frequency__c='Daily';
        PreAssesment_SHA_PTH_MH_TH.getPickListValuesIntoListforSAH();
        Test.stopTest();
    }
     @isTest
    static void TestgetPickListValuesIntoListforMH()
    {
        Test.startTest();
        Medication_History__c ob2=new Medication_History__c();
        ob2.Name_of_the_Medication__c='Detox';
      
       // ob2.Frequency__c='Daily';
        PreAssesment_SHA_PTH_MH_TH.getPickListValuesforMedication();
        Test.stopTest();
    }
    
}