SOURCE/objects/Medication_History__c.object
<CustomObject>
    <fields>
        <fullName>Current_Compliance__c</fullName>
        <label>Current Compliance</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_of_Last_Use__c</fullName>
        <label>Date of Last Use</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Dosage__c</fullName>
        <label>Dosage</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <label>Frequency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Length_of_Prescription__c</fullName>
        <label>Length of Prescription</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pre_Assessment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pre-Assessment</label>
        <referenceTo>PreAssesment__c</referenceTo>
        <relationshipLabel>Medication History</relationshipLabel>
        <relationshipName>Medication_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Medication History</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Medication History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medication History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SOURCE/objects/PreAssesment__c.object
<CustomObject>
    <fields>
        <fullName>Patient_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Pre-Assessments</relationshipLabel>
        <relationshipName>Pre_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pre-Assessment</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>PreAssesment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pre-Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SOURCE/objects/Substance_Abuse_History__c.object
<CustomObject>
    <fields>
        <fullName>Age_of_first_use__c</fullName>
        <label>Age of first use</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Daily_Amount__c</fullName>
        <label>Daily Amount</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Drug__c</fullName>
        <label>Substance Used</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alcohol</fullName>
                </value>
                <value>
                    <fullName>LSD</fullName>
                </value>
                <value>
                    <fullName>Mushrooms</fullName>
                </value>
                <value>
                    <fullName>Ecstasy</fullName>
                </value>
                <value>
                    <fullName>Marijuana</fullName>
                </value>
                <value>
                    <fullName>Heroin</fullName>
                </value>
                <value>
                    <fullName>Klonopin</fullName>
                </value>
                <value>
                    <fullName>Cocaine</fullName>
                </value>
                <value>
                    <fullName>Barbiturates</fullName>
                </value>
                <value>
                    <fullName>Valium</fullName>
                </value>
                <value>
                    <fullName>Ativan</fullName>
                </value>
                <value>
                    <fullName>Xanax</fullName>
                </value>
                <value>
                    <fullName>Librium</fullName>
                </value>
                <value>
                    <fullName>Crack Cocaine</fullName>
                </value>
                <value>
                    <fullName>Crystal Meth</fullName>
                </value>
                <value>
                    <fullName>Bath Salts</fullName>
                </value>
                <value>
                    <fullName>Adderall</fullName>
                </value>
                <value>
                    <fullName>Caffeine</fullName>
                </value>
                <value>
                    <fullName>Cigarettes</fullName>
                </value>
                <value>
                    <fullName>PCP</fullName>
                </value>
                <value>
                    <fullName>Angel Dust</fullName>
                </value>
                <value>
                    <fullName>Synthetic Marijuana</fullName>
                </value>
                <value>
                    <fullName>THC</fullName>
                </value>
                <value>
                    <fullName>Acid</fullName>
                </value>
                <value>
                    <fullName>Fentanyl</fullName>
                </value>
                <value>
                    <fullName>Percocet</fullName>
                </value>
                <value>
                    <fullName>Morphine</fullName>
                </value>
                <value>
                    <fullName>Kratom</fullName>
                </value>
                <value>
                    <fullName>Vicodin</fullName>
                </value>
                <value>
                    <fullName>Dilaudid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <label>Frequency</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Last_Use__c</fullName>
        <label>Last Use</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Orally</fullName>
                </value>
                <value>
                    <fullName>Intravenously</fullName>
                </value>
                <value>
                    <fullName>Intramusculary</fullName>
                </value>
                <value>
                    <fullName>Nasally</fullName>
                </value>
                <value>
                    <fullName>Inhalation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pre_Assessment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pre-Assessment</label>
        <referenceTo>PreAssesment__c</referenceTo>
        <relationshipLabel>Substance Abuse History</relationshipLabel>
        <relationshipName>Substance_Abuse_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Substance Abuse History</label>
    <nameField>
        <displayFormat>SAH-{000}</displayFormat>
        <label>Substance Abuse History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Substance Abuse History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SOURCE/objects/Treatment_History__c.object
<CustomObject>
    <fields>
        <fullName>Facility__c</fullName>
        <label>Facility</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Length_of_Sobriety_Achieved__c</fullName>
        <label>Length of Sobriety Achieved</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Length_of_Stay__c</fullName>
        <label>Length of Stay</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level_Of_Care__c</fullName>
        <label>Level Of Care</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Detox</fullName>
                </value>
                <value>
                    <fullName>Residential</fullName>
                </value>
                <value>
                    <fullName>IOP</fullName>
                </value>
                <value>
                    <fullName>Day-Night/PHP</fullName>
                </value>
                <value>
                    <fullName>OP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pre_Assessment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pre-Assessment</label>
        <referenceTo>PreAssesment__c</referenceTo>
        <relationshipLabel>Treatment History</relationshipLabel>
        <relationshipName>Treatment_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type_of_Discharge__c</fullName>
        <label>Type of Discharge</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Completed Successfully</fullName>
                </value>
                <value>
                    <fullName>AMA</fullName>
                </value>
                <value>
                    <fullName>Therapeutic Discharge</fullName>
                </value>
                <value>
                    <fullName>Therapeutic Transfer</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Treatment History</label>
    <nameField>
        <displayFormat>TH-{000}</displayFormat>
        <label>Treatment History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SOURCE/classes/PdfHealperTest.cls
/**
 * PreAssesment export as pdf test class
 * 
 **/
@istest
public class PdfHealperTest {

     @isTest
    static void testgetmeth1()
    {
         Account a  = new Account(Name='TestAccount');
         insert a;
        Opportunity o = new Opportunity();
        o.Name='Test';
        o.AccountId=a.Id;
        o.CloseDate=Date.today();
        o.StageName='VOB in Progress';
        insert o;
        PreAssesment__c p = new PreAssesment__c(Patient_Name__c=o.Id);
        insert p;
        Substance_Abuse_History__c s=new Substance_Abuse_History__c();
        s.Drug__c='Alcohol';
        s.Last_Use__c=System.today();
        s.Daily_Amount__c='two';
        s.Pre_Assessment__c=p.Id;
        s.Method__c='oral';
        s.Age_of_first_use__c='a';
        s.Frequency__c='Daily';
        insert s;
        
    Test.startTest();
    PdfHelper.getmeth1();
    Test.stopTest();
        
     PageReference pref = Page.PreAssesment_ExportAsPdf;
     pref.getParameters().put('id', p.id);
    Test.setCurrentPage(pref);

    ApexPages.StandardController sc = new ApexPages.StandardController(p);

    PdfHelper mc = new PdfHelper(sc);
        
    }

    
    
    
    @isTest
    static void testgetmeth2()
    {
        Account a  = new Account(Name='TestAccount');
    insert a;
    Opportunity o = new Opportunity();
        o.Name='Test';
        o.AccountId=a.Id;
        o.CloseDate=Date.today();
        o.StageName='VOB in Progress';
         insert o;
         PreAssesment__c p = new PreAssesment__c(Patient_Name__c=o.Id);
         insert p;
        Medication_History__c md=new Medication_History__c();
        md.Pre_Assessment__c=p.Id;
        md.Date_of_Last_Use__c=System.today();
        md.Frequency__c='one';
        md.Current_Compliance__c='explain';
        md.Length_of_Prescription__c='Two';
        md.Dosage__c='one';
        insert md;
        
    Test.startTest();
    PdfHelper.getmeth2();
    Test.stopTest();
        
    PageReference pref = Page.PreAssesment_ExportAsPdf;
    pref.getParameters().put('id', p.id);
    Test.setCurrentPage(pref);

    ApexPages.StandardController sc = new ApexPages.StandardController(p);

    PdfHelper mc = new PdfHelper(sc);
        
    }
    
    @isTest
    static void testgetmeth3()
    {
        Account a  = new Account(Name='TestAccount');
        insert a;
        Opportunity o = new Opportunity();
        o.Name='Test';
        o.AccountId=a.Id;
        o.CloseDate=Date.today();
        o.StageName='VOB in Progress';
        insert o;
        PreAssesment__c p = new PreAssesment__c(Patient_Name__c=o.Id);
        insert p;
        Treatment_History__c th=new Treatment_History__c();
        th.Level_Of_Care__c='Detox';
        th.Facility__c='a';
        th.Length_of_Sobriety_Achieved__c='one';
        th.Type_of_Discharge__c='Completion';
        th.Pre_Assessment__c=p.Id;
        th.Length_of_Stay__c='one';
        insert th;
        
    Test.startTest();
    PdfHelper.getmeth3();
    Test.stopTest();
        
    PageReference pref = Page.PreAssesment_ExportAsPdf;
    pref.getParameters().put('id', p.id);
    Test.setCurrentPage(pref);

    ApexPages.StandardController sc = new ApexPages.StandardController(p);

    Pdfhelper mc = new Pdfhelper(sc);
        
    }

}