SOURCE/objects/Payor__c.object
<CustomObject>
    <label>Payor</label>
    <nameField>
        <label>Payor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SOURCE/objects/VOB__c.object
<CustomObject>
    <fields>
        <fullName>Insurance_Responsibility__c</fullName>
        <label>Insurance Responsibility</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Patient_Responsibility__c</fullName>
        <label>Patient Responsibility</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>VOB</label>
    <nameField>
        <displayFormat>VOB-{0000}</displayFormat>
        <label>VOB Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VOBs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SOURCE/classes/FetchPayerDataTest.cls
@istest
public class FetchPayerDataTest {

    @istest(seealldata=true)
    static void PayorDataTest(){
        List<Payor__c> Plist=[select id,name from Payor__C Limit 1];
        Payor__c p=new Payor__c();
        insert p;
        FetchPayerData.getPayerDataWithValue(p.id);
    }
    public testMethod static void UpdateVob(){
      test.startTest();
        Payor__c p=new Payor__c();
        insert p;
        VOB__c v=new VOB__c();
      insert v;
        Decimal d=1.0;
        Decimal i=2.0;
        v.Insurance_Responsibility__c=d;
        v.Patient_Responsibility__c=i;
        update v;
        test.stopTest();
        FetchPayerData.insertInsuranceData(v.id, d, i);
    }
}