SOURCE/objects/Payor__c.object
<CustomObject>
    <fields>
        <fullName>Allowable_Detox__c</fullName>
        <label>Allowable Detox</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Allowable_IOP__c</fullName>
        <label>Allowable IOP</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Allowable_ITR__c</fullName>
        <label>Allowable IPR</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Allowable_OP__c</fullName>
        <label>Allowable OP</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Allowable_PHP__c</fullName>
        <label>Allowable PHP</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Allowable_RTC__c</fullName>
        <label>Allowable RTC</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Payor</label>
    <nameField>
        <label>Payor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SOURCE/objects/VOB__c.object
<CustomObject>
    <fields>
        <fullName>Insurance_Responsibility__c</fullName>
        <label>Insurance Responsibility</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Patient_Responsibility__c</fullName>
        <label>Patient Responsibility</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>VOB</label>
    <nameField>
        <displayFormat>VOB-{0000}</displayFormat>
        <label>VOB Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VOBs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SOURCE/classes/FetchPayerData.cls
//FetchPayerData_test is test class
public class FetchPayerData {

    @auraEnabled
    public static  Payor__c getPayerDataWithValue(String providerId){
        List<Payor__c> payerData = new List<Payor__c>();
        if(String.isNotBlank(providerId)){
            payerData = [SELECT Id, Name, Allowable_PHP__c, 
                                    Allowable_IOP__c, Allowable_detox__c,Allowable_ITR__c,Allowable_OP__c,Allowable_RTC__c FROM Payor__c where Id =:providerId];
        }
        return payerData[0];
    }
    @auraEnabled
    public static void insertInsuranceData(string ids, Decimal IR, Decimal PR){
        
       
        VOB__c v=new VOB__c(id=ids);
        
        v.Insurance_Responsibility__c=IR;
        v.Patient_Responsibility__c=PR;
        
        system.debug('beforeupdate'+v);
        update v;
        system.debug('afterupdate'+v);
        
    }
}