SOURCE/objects/PreAssesment__c.object
<CustomObject>
    <fields>
        <fullName>Patient_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Pre-Assessments</relationshipLabel>
        <relationshipName>Pre_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pre-Assessment</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>PreAssesment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pre-Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SOURCE/objects/Treatment_History__c.object
<CustomObject>
    <fields>
        <fullName>Date_of_Episode__c</fullName>
        <label>Date of Episode</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Facility__c</fullName>
        <label>Facility</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Length_of_Sobriety_Achieved__c</fullName>
        <label>Length of Sobriety Achieved</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Length_of_Stay__c</fullName>
        <label>Length of Stay</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level_Of_Care__c</fullName>
        <label>Level Of Care</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Detox</fullName>
                </value>
                <value>
                    <fullName>Residential</fullName>
                </value>
                <value>
                    <fullName>IOP</fullName>
                </value>
                <value>
                    <fullName>Day-Night/PHP</fullName>
                </value>
                <value>
                    <fullName>OP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_Discharge__c</fullName>
        <label>Type of Discharge</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Completed Successfully</fullName>
                </value>
                <value>
                    <fullName>AMA</fullName>
                </value>
                <value>
                    <fullName>Therapeutic Discharge</fullName>
                </value>
                <value>
                    <fullName>Therapeutic Transfer</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Treatment History</label>
    <nameField>
        <displayFormat>TH-{000}</displayFormat>
        <label>Treatment History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SOURCE/classes/PreAssesment_TH_Test.cls
@istest
public class PreAssesment_TH_Test {

     @isTest
    static void saveSubsanceAbuseHistoryRecords()
    {
        Test.startTest();
        Treatment_History__c ob=new Treatment_History__c();
        List<Treatment_History__c> result=new List<Treatment_History__c>();
        Account ac=new Account();
            
        ac.Name='Mr. ab bc cd';
        insert ac;
         Opportunity op=new Opportunity();
         op.Name='av';
      
         op.CloseDate=System.today();
        op.StageName='Active';
        op.AccountId=ac.Id;
        insert op;
        PreAssesment__c ob1=new PreAssesment__c();
        ob1.Patient_Name__c=op.Id;
        insert ob1;
        ob.Facility__c='LSD';
        ob.Level_Of_Care__c='IOP';
        ob.Length_of_Stay__c='LONG';
        ob.Length_of_Sobriety_Achieved__c='Rare';
        ob.Type_of_Discharge__c='None';
        ob.Date_of_Episode__c =system.today();
            
        result.add(ob);
        PreAssesment_PTH.saveContacts(result);
        Test.stopTest();
    }
    @isTest
    static void TestgetPickListValuesIntoListforSAH()
    {
        Test.startTest();
        Treatment_History__c ob2=new Treatment_History__c();
        ob2.Level_Of_Care__c='IOP';
        ob2.Type_of_Discharge__c='None';
        PreAssesment_PTH.getPickListValuesIntoList();
        Test.stopTest();
    }
}