SOURCE/objects/Treatment_History__c.object
<CustomObject>
    <fields>
        <fullName>Level_Of_Care__c</fullName>
        <label>Level Of Care</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Detox</fullName>
                </value>
                <value>
                    <fullName>Residential</fullName>
                </value>
                <value>
                    <fullName>IOP</fullName>
                </value>
                <value>
                    <fullName>Day-Night/PHP</fullName>
                </value>
                <value>
                    <fullName>OP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_Discharge__c</fullName>
        <label>Type of Discharge</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Completed Successfully</fullName>
                </value>
                <value>
                    <fullName>AMA</fullName>
                </value>
                <value>
                    <fullName>Therapeutic Discharge</fullName>
                </value>
                <value>
                    <fullName>Therapeutic Transfer</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Treatment History</label>
    <nameField>
        <displayFormat>TH-{000}</displayFormat>
        <label>Treatment History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treatment History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SOURCE/classes/PreAssesment_PTH.cls
public class PreAssesment_PTH {

   
   @AuraEnabled
    public static void saveContacts(List<Treatment_History__c> ListPTH){
        Insert ListPTH;
    }
   
    @AuraEnabled       
    public static List<List<String>> getPickListValuesIntoList()
    {
      List<List<string>> masterList = new List<List<string>>();
        List<string> options = new List<string>();
         List<string> options2 = new List<string>();
      
       
        //String a= 'Primary_Drug_Type__c';
        Schema.DescribeFieldResult fieldResult = Treatment_History__c.Level_Of_Care__c.getDescribe();
          Schema.DescribeFieldResult fieldResultsub = Treatment_History__c.Type_of_Discharge__c.getDescribe();
          
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry f : ple)
        {
           
            options.add( f.getValue());
        }   
         masterList.add(options);
       
          List<Schema.PicklistEntry> plesub = fieldResultsub.getPicklistValues();
        for( Schema.PicklistEntry fsub : plesub)
        {
           
            options2.add( fsub.getValue());
        }    
        masterList.add(options2);
       
       
       
        return masterList;
    }
}